layout_spectrum: 0.5032250143121928
typography_spectrum: 0.5798676335252821
color:
  brandStrength: 0.950525687308982
  lightness: 0.8554601452779025
  saturation: 0.0879492717795074
  rhythmicContrast: 0.7286786788608879
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
author:
  name: ''
name: ramblingpolak
navigation:
  - name: LinkedIn
    url: 'http://adamkunicki.com'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3f298af4-71a1-40b4-9a6c-42f93eb2aa20.png
title: ramblings from @ramblingpolak
